style:
  tag:
    color: white # Possible values: https://bit.ly/3gloNNI
    width_percentage: 25
    min_width: 10
  comment:
    color: blue
    width_percentage: 40
    min_width: 40
  snippet:
    color: white

finder:
  command: fzf
  # overrides: --tac # equivalent to the --fzf-overrides option
  # overrides_var: --tac # equivalent to the --fzf-overrides-var option

cheats:
  paths:
    - /home/sn/.local/share/navi/cheats
    - /home/sn/.config/navi/cheats
    - /path/to/some/dir # on unix-like os

# search:
# tags: git,!checkout # equivalent to the --tag-rules option

shell:
  command: zsh

