dialect = "uk" # "us" or "uk"
timezone = "local"
auto_sync = false
update_check = true
sync_frequency = "24h"
inline_height = 0
invert = false
show_help = true
secrets_filter = true
enter_accept = false
prefers_reduced_motion = true
search_mode = "fuzzy"
search_mode_shell_up_key_binding = "prefix"
filter_mode = "host"
style = "compact"
exit_mode = "return-original"
